export const translations = {
  en: {
    title: "OZORA 2026 TIMETABLE",
    searchPlaceholder: "Search artist, stage, type...",
    favoritesOnly: "My Schedule Only",
    stageFilter: "Stages",
    dayFilter: "Days",
    simulatingTime: "Simulated Time",
    nowPlaying: "Now Playing",
    nextUp: "Next Up",
    noSetsFound: "No sets match your criteria.",
    stage: "Stage",
    time: "Time",
    type: "Type",
    allStages: "All Stages",
    allDays: "All Days",
    simulatedTimeDesc: "Drag slider to test schedule during festival",
    backToRealTime: "Use Real Time",
    favoritesEmpty: "Tap the star on any artist to add them to your custom schedule!",
    artist: "Artist",
    shareSchedule: "Share Schedule",
    copiedToClipboard: "Share link copied to clipboard!",
    sharedScheduleImported: "Shared schedule added to your favorites!",
    cookieTitle: "Cookie Preferences",
    cookieMessage: "We use cookies to improve your browsing experience and analyze site traffic.",
    cookieAcceptAll: "Accept All",
    cookieDeclineAll: "Decline All",
    cookieCustomize: "Customize Preferences",
    cookieSave: "Save My Choices",
    cookieNecessaryTitle: "Strictly Necessary",
    cookieNecessaryDesc: "Required for basic website functions (e.g. language selection, saved schedule, and consent state). Cannot be disabled.",
    cookieAnalyticsTitle: "Statistics & Performance",
    cookieAnalyticsDesc: "Collects anonymous details on site traffic, popular pages, and session duration using Google Analytics.",
    cookieFunctionalTitle: "Functional Settings",
    cookieFunctionalDesc: "Remember user display options and customizations.",
    cookieMarketingTitle: "Marketing & Targeting",
    cookieMarketingDesc: "Used to deliver relevant marketing campaigns or tracking (not used currently).",
    cookiePrivacyLink: "Privacy Policy",
    copyright: "© 2026 Bersaglio. All rights reserved.",
    developedWithLove: "Developed with love by AI agents",
    installPrompt: "Install the app to your home screen for offline use at the festival",
    installBtn: "Install",
    installDismiss: "Not now",
    priorityMust: "Must See",
    priorityWant: "Want to See",
    priorityMaybe: "Maybe",
    filterMustSee: "Must See Only",
    addNote: "Add note...",
    notePlaceholder: "Personal note (max 100 chars)",
    noteLabel: "Note",
    conflicts: "Conflicts",
    conflictsWith: "Overlaps with",
    conflictMinutes: "min",
    shareSchedule: "Share",
    copyLink: "Copy Link",
    showQR: "Show QR",
    exportImage: "Export Image",
    qrTitle: "Scan to import my schedule",
    linkCopied: "Share link copied to clipboard!",
    exportTitle: "My Ozora 2026 Schedule",
    exportFooter: "Made with ozora2026.app",
    exportSuccess: "Image saved!",
    importTitle: "Someone shared their schedule with you!",
    importSetsCount: "sets",
    importAll: "Import All to My Schedule",
    saveAsFriend: "Save as Friend's Schedule",
    justView: "Just View",
    friendNamePlaceholder: "Friend's name",
    friendSchedules: "Friend Schedules",
    friendSets: "sets",
    compare: "Compare",
    remove: "Remove",
    bothPicked: "Both picked",
    onlyYou: "Only you",
    onlyFriend: "Only",
    addToMine: "Add to mine",
    comparingWith: "Comparing with",
    friendRemoved: "Friend's schedule removed",
    friendSaved: "Schedule saved!",
    maxFriendsReached: "Max 10 friend schedules"
  },
  he: {
    title: "לוח הופעות אוזורה 2026",
    searchPlaceholder: "חיפוש אמן, במה, סוג...",
    favoritesOnly: "הלוח שלי בלבד",
    stageFilter: "במות",
    dayFilter: "ימים",
    simulatingTime: "זמן מדומה",
    nowPlaying: "מנגנים עכשיו",
    nextUp: "הבאים בתור",
    noSetsFound: "לא נמצאו הופעות תואמות.",
    stage: "במה",
    time: "שעה",
    type: "סוג",
    allStages: "כל הבמות",
    allDays: "כל הימים",
    simulatedTimeDesc: "גרור את הסליידר כדי לבדוק הופעות במהלך הפסטיבל",
    backToRealTime: "חזור לזמן אמת",
    favoritesEmpty: "לחץ על הכוכב ליד שם האמן כדי להוסיף אותו ללוח האישי שלך!",
    artist: "אמן",
    shareSchedule: "שתף לוח זמנים",
    copiedToClipboard: "קישור השיתוף הועתק ללוח!",
    sharedScheduleImported: "לוח ההופעות ששותף איתך התווסף למועדפים!",
    cookieTitle: "הגדרות עוגיות (Cookies)",
    cookieMessage: "אנחנו משתמשים בקבצי עוגיות כדי לשפר את חווית הגלישה והאנליטיקס באתר.",
    cookieAcceptAll: "אישור של כל העוגיות",
    cookieDeclineAll: "דחיית עוגיות",
    cookieCustomize: "התאמת העדפות",
    cookieSave: "שמור את הבחירות שלי",
    cookieNecessaryTitle: "עוגיות הכרחיות / חיוניות",
    cookieNecessaryDesc: "עוגיות שבלעדיהן האתר לא יכול לתפקד (כמו שפת האתר, המועדפים שלך והגדרות הפרטיות הללו).",
    cookieAnalyticsTitle: "עוגיות סטטיסטיקה וביצועים",
    cookieAnalyticsDesc: "מאפשר איסוף נתונים אנונימיים על אופן השימוש באתר באמצעות גוגל אנליטיקס (עמודים פופולריים, זמן שהייה וכו').",
    cookieFunctionalTitle: "עוגיות פונקציונליות",
    cookieFunctionalDesc: "עוגיות הזוכרות את הגדרות התצוגה המותאמות אישית של המשתמש.",
    cookieMarketingTitle: "עוגיות שיווק ופרסום",
    cookieMarketingDesc: "משמשות למעקב אחר משתמשים להצגת פרסומות מותאמות אישית (אינן בשימוש כרגע באתר).",
    cookiePrivacyLink: "למדיניות הפרטיות המלאה",
    copyright: "זכויות יוצרים ל-Bersaglio © 2026",
    developedWithLove: "פותח באהבה על ידי סוכני AI",
    installPrompt: "התקן את האפליקציה למסך הבית לשימוש אופליין בפסטיבל",
    installBtn: "התקן",
    installDismiss: "לא עכשיו",
    priorityMust: "חובה",
    priorityWant: "רוצה לראות",
    priorityMaybe: "אולי",
    filterMustSee: "רק חובה",
    addNote: "הוסף הערה...",
    notePlaceholder: "הערה אישית (עד 100 תווים)",
    noteLabel: "הערה",
    conflicts: "התנגשויות",
    conflictsWith: "חופף עם",
    conflictMinutes: "דק׳",
    shareSchedule: "שתף לוח",
    copyLink: "העתק קישור",
    showQR: "הצג QR",
    exportImage: "ייצא תמונה",
    qrTitle: "סרקו כדי לייבא את הלוח שלי",
    linkCopied: "קישור השיתוף הועתק ללוח!",
    exportTitle: "הלוח שלי — אוזורה 2026",
    exportFooter: "נוצר עם ozora2026.app",
    exportSuccess: "התמונה נשמרה!",
    importTitle: "מישהו שיתף איתך את הלוח שלו!",
    importSetsCount: "הופעות",
    importAll: "ייבא הכל ללוח שלי",
    saveAsFriend: "שמור כלוח של חבר/ה",
    justView: "רק צפייה",
    friendNamePlaceholder: "שם החבר/ה",
    friendSchedules: "לוחות חברים",
    friendSets: "הופעות",
    compare: "השווה",
    remove: "הסר",
    bothPicked: "שניכם בחרתם",
    onlyYou: "רק אתה",
    onlyFriend: "רק",
    addToMine: "הוסף ללוח שלי",
    comparingWith: "משווה עם",
    friendRemoved: "הלוח של החבר/ה הוסר",
    friendSaved: "הלוח נשמר!",
    maxFriendsReached: "ניתן לשמור עד 10 לוחות חברים"
  }
};
