export const translations = {
  en: {
    title: "OZORA 2026 TIMETABLE",
    searchPlaceholder: "Search artist, stage, type...",
    favoritesOnly: "My Schedule Only",
    stageFilter: "Stages",
    dayFilter: "Days",
    simulatingTime: "Simulated Time",
    nowPlaying: "Now Playing",
    nextUp: "Next Up",
    noSetsFound: "No sets match your criteria.",
    stage: "Stage",
    time: "Time",
    type: "Type",
    allStages: "All Stages",
    allDays: "All Days",
    simulatedTimeDesc: "Drag slider to test schedule during festival",
    backToRealTime: "Use Real Time",
    favoritesEmpty: "Tap the star on any artist to add them to your custom schedule!",
    artist: "Artist",
    shareSchedule: "Share Schedule",
    copiedToClipboard: "Share link copied to clipboard!",
    sharedScheduleImported: "Shared schedule added to your favorites!",
    cookieTitle: "Cookie Preferences",
    cookieMessage: "We use cookies to improve your browsing experience and analyze site traffic.",
    cookieAcceptAll: "Accept All",
    cookieDeclineAll: "Decline All",
    cookieCustomize: "Customize Preferences",
    cookieSave: "Save My Choices",
    cookieNecessaryTitle: "Strictly Necessary",
    cookieNecessaryDesc: "Required for basic website functions (e.g. language selection, saved schedule, and consent state). Cannot be disabled.",
    cookieAnalyticsTitle: "Statistics & Performance",
    cookieAnalyticsDesc: "Collects anonymous details on site traffic, popular pages, and session duration using Google Analytics.",
    cookieFunctionalTitle: "Functional Settings",
    cookieFunctionalDesc: "Remember user display options and customizations.",
    cookieMarketingTitle: "Marketing & Targeting",
    cookieMarketingDesc: "Used to deliver relevant marketing campaigns or tracking (not used currently).",
    cookiePrivacyLink: "Privacy Policy",
    dataDisclaimer: "Set times, genres and other data may be incomplete or wrong. Always double-check on site.",
    copyright: "© 2026 Bersaglio. All rights reserved.",
    developedWithLove: "Developed with love by AI agents",
    installPrompt: "Open once with internet before the festival, then install for offline use",
    installBtn: "Install",
    installDismiss: "Not now",
    footerInstallPrompt: "Open once with internet before the festival to save it offline.",
    footerInstallBtn: "Install now",
    footerInstallHelp: "On iPhone: open this page online first, then tap Share and Add to Home Screen.",
    pwaUpdateTitle: "A new version is available",
    pwaUpdateBody: "Update now to get the latest changes.",
    pwaUpdateNow: "Update now",
    pwaUpdateSkip: "Skip",
    pwaUpdateDismiss: "Dismiss update prompt",
    priorityMust: "Must See",
    priorityWant: "Want to See",
    priorityMaybe: "Maybe",
    filterMustSee: "Must See Only",
    addNote: "Add note...",
    notePlaceholder: "Personal note (max 100 chars)",
    noteLabel: "Note",
    conflicts: "Conflicts",
    conflictsWith: "Overlaps with",
    conflictMinutes: "min",
    copyLink: "Copy Link",
    showQR: "Show QR",
    exportImage: "Export Image",
    qrTitle: "Scan to import my schedule",
    linkCopied: "Share link copied to clipboard!",
    exportTitle: "My Ozora 2026 Schedule",
    exportFooter: "Made with ozora2026.app",
    exportSuccess: "Image saved!",
    importTitle: "Someone shared their schedule with you!",
    importSetsCount: "sets",
    importAll: "Import All to My Schedule",
    saveAsFriend: "Save as Friend's Schedule",
    justView: "Just View",
    friendNamePlaceholder: "Friend's name",
    friendSchedules: "Friend Schedules",
    friendSets: "sets",
    compare: "Compare",
    remove: "Remove",
    bothPicked: "Both picked",
    onlyYou: "Only you",
    onlyFriend: "Only",
    addToMine: "Add to mine",
    comparingWith: "Comparing with",
    friendRemoved: "Friend's schedule removed",
    friendSaved: "Schedule saved!",
    maxFriendsReached: "Max 10 friend schedules",
    view: "View",
    viewingSchedule: "Viewing {name}'s Schedule",
    backToMySchedule: "Back to My Schedule",
    addToMySchedule: "Add to My Schedule",
    removeFromMySchedule: "Remove from My Schedule",
    mapTab: "Map",
    showOnMap: "Show on map",
    stageClosed: "Stage closed",
    nextOpening: "Next opening",
    walkTime: "walk",
    showAll: "Show All",
    downloadingMap: "Downloading map for offline use...",
    connectedToSingle: "Connected to 1 more show",
    connectedToMulti: "Connected to {count} more shows",
    otherProjectsTitle: "Other projects at the festival",
    projectMembersTitle: "Project members performing at the festival",
    alsoPerformsUnder: "{name} also performs under {projects}",
    mapReady: "Map ready for offline use!",
    gpsUnavailable: "GPS unavailable",
    centerOnMe: "Center on me",
    navigate: "Navigate",
    viewInTimetable: "View in Timetable",
    distance: "away",
    themeAuto: "Auto",
    themeDay: "Day",
    themeSunset: "Sunset",
    themeNight: "Night",
    themeSunrise: "Sunrise",
    themePinned: "Theme locked",
    themeUnpinned: "Theme follows time",
    themeLabel: "Atmosphere",
    listenYouTube: "Listen on YouTube",
    listenSoundCloud: "Listen on SoundCloud",
    listenMusic: "Listen to music",
    viewModeGrid: "Grid View",
    viewModeStages: "Stage View",
    artistsCount: "artists",
    exportCsv: "Export to Excel (CSV)",
    printSchedule: "Print Schedule",
    exportImageCosmic: "Export Image (Cosmic Night)",
    exportImageTheme: "Export Image (Active Theme)",
    shareQuickAccess: "Share & Access",
    exportMedia: "Media & Image Export",
    exportFilesPrint: "Files & Printing",
    friendScheduleUpdated: "Updated {name}'s schedule and coordination notes!",
    coordinationNote: "Coordination Note",
    coordinationNotePlaceholder: "Meet at... (max 100 chars)",
    shareBackWith: "Share Back with {name}",
    recentSearches: "Recent Searches",
    quickFilters: "Quick Filters",
    nowPlayingTag: "Now Playing",
    nextUpTag: "Next Up",
    myScheduleTag: "My Schedule",
    matchRelated: "Related to {name}",
    matchFriend: "On {name}'s schedule",
    matchNote: "Matches note: {snippet}",
    matchCoordinationNote: "{name}'s meet note: {snippet}",
    matchPriority: "Priority: {level}",
    clearHistory: "Clear",
    emptyHistory: "No recent searches",
    botWelcome: "Hey there! 🌌 I am your offline Ozora guide. Ask me about artist schedules (e.g. 'Astrix'), stages, packing lists, or how to use this app. What would you like to know?",
    botInputPlaceholder: "Ask me anything (e.g., Astrix, Dome)...",
    botFallback: "I couldn't find details about that in the offline guide. When you have internet, you can check the official site: https://ozora.hu",
    botHowToUseTitle: "How to use the Ozora 2026 App:",
    botHowToUseDesc: "• Tap the ⭐️ star icon next to any artist to add them to 'My Schedule'.\n• Tap 'Share Schedule' in My Schedule to share a link or show a QR code to your friends.\n• Tap 'Compare' in Friend Schedules to find overlapping sets.\n• In the Map, tap the ⛺️ tent icon (or long-press the map) to pin your camp site.\n• Open the app once with internet before the festival, install it as a PWA, and everything will work 100% offline!",
    botQuickReplyNowPlaying: "Who's playing now?",
    botQuickReplyHowToUse: "How to use the app?",
    botQuickReplyChecklist: "Packing checklist",
    botQuickReplyMedical: "Where is medical?",
    botArtistPlaying: "Here are the set times for {artist}:",
    botStageInfo: "Here is what I found about {stage}:",
    botGuideSnippet: "Here is a tip from the guide:",
    botReadGuide: "Read Full Guide",
    botAddToSchedule: "Add to Schedule",
    botAddedToSchedule: "Added!",
    botViewInTimetable: "View in Timetable",
    botShowOnMap: "Show on Map",
    botChatTitle: "Cosmic Guide (Offline)",
    botOpenMap: "Open Map",
    botOpenSchedule: "Open My Schedule",
    botOpenTimetable: "Open Timetable",
    botOpenGuide: "Open Guide",
    botMapResponse: "Here is the interactive festival map. You can see the locations of stages, food/stalls, camping areas, toilets, medical helper points, and your pinned campsite:",
    botScheduleResponse: "Here is your personal schedule with all the performances you starred. You can also share your schedule with friends or compare schedules:",
    botTimetableResponse: "Here is the complete festival timetable. You can browse artists, filter by days or stages, search sets, or simulate schedule changes:",
    botGuideResponse: "Here is the comprehensive festival guide, covering transport, camping, food, facilities, tickets, stages, safety and more:",
    guideBackToGuides: "Back to Guides",
    equipPageTitle: "Festival Equipment",
    equipPageSubtitle: "Personal & group checklist",
    guideMainTitle: "Festival Guide",
    guideMainSubtitleComingSoon: "Tips, advice, and orientation around Ozora Festival 2026 – coming soon!",
    guideMainSubtitle: "Tips, advice, and orientation around Ozora Festival 2026",
    guideTopicsCount: "{count} topics",
    equipBackupLoaded: "Backup loaded successfully!",
    equipBackupInvalid: "Invalid backup file.",
    equipBackupReadError: "Error reading backup file.",
    equipPrintingTitle: "Printing {title}",
    equipCheckedCount: "checked",
    equipNoItemsMatch: "No items match the current filter.",
    equipTopicPrintPrefix: "Topic: {heading}",
    equipQuantityLabel: "Quantity",
    equipQuantityForAria: "Quantity for {item}",
    equipNoteForAria: "Note for {item}",
    equipNotePlaceholder: "Who's bringing it, type, size...",
    equipInfoNote: "Once you've checked off your gear, you can export it to Excel, print it, or save a backup.",
    equipExportBackupBtn: "Export & Backup",
    equipExportExcelSection: "Data Export (Excel)",
    equipExportExcelAll: "Branded Excel export (all equipment)",
    equipExportExcelChecked: "Branded Excel export (checked items only)",
    equipPrintMediaSection: "Print & Media",
    equipPrintAll: "Print list (all equipment)",
    equipPrintChecked: "Print checked items only",
    equipExportImageAll: "Export as readable images (all equipment)",
    equipExportImageChecked: "Export as readable images (checked items only)",
    equipBackupSection: "Offline Backup (JSON)",
    equipSaveBackup: "Save backup file",
    equipLoadBackup: "Load backup file",
    equipSearchPlaceholder: "Search item or hint...",
    equipClearSearch: "Clear search",
    equipFilterAll: "All",
    equipFilterUnchecked: "Not checked yet",
    equipFilterChecked: "Checked",
    equipTabShared: "Group",
    equipTabPersonal: "Personal",
    equipBrandNote: "The Ozora 2026 list is here to help you prepare. Always double-check flight limits, weather, and official festival guidelines.",
    equipColCategory: "Category",
    equipColItem: "Item",
    equipColUserNote: "User Note",
    equipColOzoraNote: "Ozora Note",
    equipColStatus: "Status",
    equipStatusChecked: "Checked",
    equipStatusUnchecked: "Not checked",
    equipNoExportItems: "No items found for this export selection.",
    equipWorksheetChecked: "Checked Items",
    equipWorksheetAll: "Equipment List",
    equipExportDescChecked: "Export of checked items only",
    equipExportDescAll: "Export of the full equipment list",
    equipBrandTitle: "OZORA 2026 · Festival Equipment List",
    equipWorksheetCoordination: "Checked Equipment",
    equipWorksheetCoordinationDesc: "Quick coordination sheet: checked items only",
    equipWorksheetFull: "Full List",
    equipWorksheetFullDesc: "Full sheet: includes unchecked items",
    equipPageMarker: "OZORA 2026 · Page {page}/{total} · ozora2026.app"
  },
  he: {
    title: "לוח הופעות אוזורה 2026",
    searchPlaceholder: "חיפוש אמן, במה, סוג...",
    favoritesOnly: "הלוח שלי בלבד",
    stageFilter: "במות",
    dayFilter: "ימים",
    simulatingTime: "זמן מדומה",
    nowPlaying: "מנגנים עכשיו",
    nextUp: "הבאים בתור",
    noSetsFound: "לא נמצאו הופעות תואמות.",
    stage: "במה",
    time: "שעה",
    type: "סוג",
    allStages: "כל הבמות",
    allDays: "כל הימים",
    simulatedTimeDesc: "גרור את הסליידר כדי לבדוק הופעות במהלך הפסטיבל",
    backToRealTime: "חזור לזמן אמת",
    favoritesEmpty: "לחץ על הכוכב ליד שם האמן כדי להוסיף אותו ללוח האישי שלך!",
    artist: "אמן",
    shareSchedule: "שתף לוח זמנים",
    copiedToClipboard: "קישור השיתוף הועתק ללוח!",
    sharedScheduleImported: "לוח ההופעות ששותף איתך התווסף למועדפים!",
    cookieTitle: "הגדרות עוגיות (Cookies)",
    cookieMessage: "אנחנו משתמשים בקבצי עוגיות כדי לשפר את חווית הגלישה והאנליטיקס באתר.",
    cookieAcceptAll: "אישור של כל העוגיות",
    cookieDeclineAll: "דחיית עוגיות",
    cookieCustomize: "התאמת העדפות",
    cookieSave: "שמור את הבחירות שלי",
    cookieNecessaryTitle: "עוגיות הכרחיות / חיוניות",
    cookieNecessaryDesc: "עוגיות שבלעדיהן האתר לא יכול לתפקד (כמו שפת האתר, המועדפים שלך והגדרות הפרטיות הללו).",
    cookieAnalyticsTitle: "עוגיות סטטיסטיקה וביצועים",
    cookieAnalyticsDesc: "מאפשר איסוף נתונים אנונימיים על אופן השימוש באתר באמצעות גוגל אנליטיקס (עמודים פופולריים, זמן שהייה וכו').",
    cookieFunctionalTitle: "עוגיות פונקציונליות",
    cookieFunctionalDesc: "עוגיות הזוכרות את הגדרות התצוגה המותאמות אישית של המשתמש.",
    cookieMarketingTitle: "עוגיות שיווק ופרסום",
    cookieMarketingDesc: "משמשות למעקב אחר משתמשים להצגת פרסומות מותאמות אישית (אינן בשימוש כרגע באתר).",
    cookiePrivacyLink: "למדיניות הפרטיות המלאה",
    dataDisclaimer: "שעות ההופעות, הז'אנרים ומידע נוסף עשויים להיות חסרים או שגויים. תמיד יש לוודא באתר.",
    copyright: "זכויות יוצרים ל-Bersaglio © 2026",
    developedWithLove: "פותח באהבה על ידי סוכני AI",
    installPrompt: "פתחו פעם אחת עם אינטרנט לפני הפסטיבל, ואז התקינו לשימוש אופליין",
    installBtn: "התקן",
    installDismiss: "לא עכשיו",
    footerInstallPrompt: "פתחו פעם אחת עם אינטרנט לפני הפסטיבל כדי לשמור לאופליין.",
    footerInstallBtn: "הורד עכשיו",
    footerInstallHelp: "באייפון: פתחו את העמוד אונליין קודם, ואז לחצו Share ו-Add to Home Screen.",
    pwaUpdateTitle: "גרסה חדשה זמינה",
    pwaUpdateBody: "אפשר לעדכן עכשיו כדי לקבל את השינויים האחרונים.",
    pwaUpdateNow: "עדכן עכשיו",
    pwaUpdateSkip: "דלג",
    pwaUpdateDismiss: "סגור הודעת עדכון",
    priorityMust: "חובה",
    priorityWant: "רוצה לראות",
    priorityMaybe: "אולי",
    filterMustSee: "רק חובה",
    addNote: "הוסף הערה...",
    notePlaceholder: "הערה אישית (עד 100 תווים)",
    noteLabel: "הערה",
    conflicts: "התנגשויות",
    conflictsWith: "חופף עם",
    conflictMinutes: "דק׳",
    copyLink: "העתק קישור",
    showQR: "הצג QR",
    exportImage: "ייצא תמונה",
    qrTitle: "סרקו כדי לייבא את הלוח שלי",
    linkCopied: "קישור השיתוף הועתק ללוח!",
    exportTitle: "הלוח שלי — אוזורה 2026",
    exportFooter: "נוצר עם ozora2026.app",
    exportSuccess: "התמונה נשמרה!",
    importTitle: "מישהו שיתף איתך את הלוח שלו!",
    importSetsCount: "הופעות",
    importAll: "ייבא הכל ללוח שלי",
    saveAsFriend: "שמור כלוח של חבר/ה",
    justView: "רק צפייה",
    friendNamePlaceholder: "שם החבר/ה",
    friendSchedules: "לוחות חברים",
    friendSets: "הופעות",
    compare: "השווה",
    remove: "הסר",
    bothPicked: "שניכם בחרתם",
    onlyYou: "רק אתה",
    onlyFriend: "רק",
    addToMine: "הוסף ללוח שלי",
    comparingWith: "משווה עם",
    friendRemoved: "הלוח של החבר/ה הוסר",
    friendSaved: "הלוח נשמר!",
    maxFriendsReached: "ניתן לשמור עד 10 לוחות חברים",
    view: "צפייה",
    viewingSchedule: "צופה בלוח של {name}",
    backToMySchedule: "חזור ללוח שלי",
    addToMySchedule: "הוסף ללוח שלי",
    removeFromMySchedule: "הסר מהלוח שלי",
    mapTab: "מפה",
    showOnMap: "הצג במפה",
    stageClosed: "הבמה סגורה",
    nextOpening: "הפתיחה הבאה",
    walkTime: "הליכה",
    showAll: "הצג הכל",
    downloadingMap: "מוריד מפה לשימוש אופליין...",
    connectedToSingle: "קשור להופעה נוספת אחת",
    connectedToMulti: "קשור ל-{count} הופעות נוספות",
    otherProjectsTitle: "פרויקטים נוספים בפסטיבל",
    projectMembersTitle: "חברי הפרויקט שמופיעים בפסטיבל",
    alsoPerformsUnder: "{name} מופיע גם במסגרת {projects}",
    mapReady: "המפה מוכנה לשימוש אופליין!",
    gpsUnavailable: "GPS לא זמין",
    centerOnMe: "מרכז עליי",
    navigate: "נווט",
    viewInTimetable: "הצג בלוח",
    distance: "מרחק",
    themeAuto: "אוטומטי",
    themeDay: "יום",
    themeSunset: "שקיעה",
    themeNight: "לילה",
    themeSunrise: "זריחה",
    themePinned: "העיצוב נעול",
    themeUnpinned: "העיצוב עוקב אחרי הזמן",
    themeLabel: "אווירה",
    listenYouTube: "האזן ביוטיוב",
    listenSoundCloud: "האזן בסאונדקלאוד",
    listenMusic: "האזן למוסיקה",
    viewModeGrid: "תצוגת גריד",
    viewModeStages: "תצוגת במות",
    artistsCount: "אמנים",
    exportCsv: "ייצוא לאקסל (CSV)",
    printSchedule: "הדפסת הלוח",
    exportImageCosmic: "ייצוא לתמונה (לילה קוסמי)",
    exportImageTheme: "ייצוא לתמונה (ערכת הנושא הפעילה)",
    shareQuickAccess: "שיתוף וגישה מהירה",
    exportMedia: "מדיה וייצוא תמונה",
    exportFilesPrint: "קבצים והדפסה",
    friendScheduleUpdated: "הלוח והתיאומים של {name} עודכנו בהצלחה!",
    coordinationNote: "הערת תיאום",
    coordinationNotePlaceholder: "ניפגש ב... (עד 100 תווים)",
    shareBackWith: "שתף בחזרה עם {name}",
    recentSearches: "חיפושים אחרונים",
    quickFilters: "סינון מהיר",
    nowPlayingTag: "מנגנים עכשיו",
    nextUpTag: "הבאים בתור",
    myScheduleTag: "הלוח שלי",
    matchRelated: "קשור ל-{name}",
    matchFriend: "בלוח של {name}",
    matchNote: "תואם להערה: {snippet}",
    matchCoordinationNote: "הערת מפגש של {name}: {snippet}",
    matchPriority: "עדיפות: {level}",
    clearHistory: "נקה",
    emptyHistory: "אין חיפושים אחרונים",
    botWelcome: "היי! 🌌 אני המדריך המקומי שלך לאוזורה. שאל אותי על שעות הופעה של אמנים (למשל 'Astrix'), במות, רשימת ציוד או איך משתמשים באפליקציה. מה תרצה לדעת?",
    botInputPlaceholder: "שאל אותי משהו (למשל, Astrix, Dome)...",
    botFallback: "לא הצלחתי למצוא מידע על כך במדריך האופליין. כשתהיה מחובר לאינטרנט, תוכל לבדוק באתר הרשמי: https://ozora.hu",
    botHowToUseTitle: "איך משתמשים באפליקציית אוזורה 2026:",
    botHowToUseDesc: "• לחץ על אייקון ה-⭐️ כוכב ליד כל אמן כדי להוסיף אותו ל-'הלוח שלי'.\n• לחץ על 'שתף לוח זמנים' בלוח שלי כדי להעתיק קישור או להציג קוד QR לחברים.\n• לחץ על 'השווה' בלוחות של חברים כדי למצוא הופעות חופפות.\n• במפה, לחץ על אייקון ה-⛺️ אוהל (או לחיצה ארוכה על המפה) כדי לסמן את מיקום האוהל שלך.\n• פתח את האפליקציה פעם אחת עם אינטרנט לפני הפסטיבל, התקן אותה כ-PWA, והכל יעבוד ב-100% אופליין!",
    botQuickReplyNowPlaying: "מי מופיע עכשיו?",
    botQuickReplyHowToUse: "איך משתמשים באפליקציה?",
    botQuickReplyChecklist: "צ'ק-ליסט ציוד",
    botQuickReplyMedical: "איפה המרפאה?",
    botArtistPlaying: "הנה שעות ההופעה של {artist}:",
    botStageInfo: "הנה מה שמצאתי על במת {stage}:",
    botGuideSnippet: "הנה טיפ מהמדריך המקומי:",
    botReadGuide: "קרא את המדריך המלא",
    botAddToSchedule: "הוסף ללוח שלי",
    botAddedToSchedule: "נוסף!",
    botViewInTimetable: "הצג בלוח הופעות",
    botShowOnMap: "הצג במפה",
    botChatTitle: "מדריך קוסמי (אופליין)",
    botOpenMap: "פתח מפה",
    botOpenSchedule: "פתח לוח אישי",
    botOpenTimetable: "פתח לוח הופעות",
    botOpenGuide: "פתח מדריך",
    botMapResponse: "הנה מפת הפסטיבל האינטראקטיבית. תוכל למצוא את מיקום הבמות, דוכני האוכל, אזורי הקמפינג, השירותים, המרפאות ואפילו לסמן את האוהל האישי שלך:",
    botScheduleResponse: "הנה הלוח האישי שלך עם כל ההופעות שסימנת בכוכב. מכאן תוכל גם לשתף את הלוח עם חברים או להשוות איתם הופעות:",
    botTimetableResponse: "הנה לוח ההופעות המלא של הפסטיבל. תוכל לצפות בכל האמנים, לסנן לפי ימים ובמות, לחפש הופעות ולסמלץ שעות:",
    botGuideResponse: "הנה מדריך הפסטיבל המלא, הכולל מידע על דרכי הגעה, קמפינג, אוכל, מתקנים, כרטיסים, במות, בטיחות ועוד:",
    guideBackToGuides: "חזרה למדריכים",
    equipPageTitle: "ציוד לפסטיבל",
    equipPageSubtitle: "צ׳ק-ליסט אישי וקבוצתי",
    guideMainTitle: "מדריך הפסטיבל",
    guideMainSubtitleComingSoon: "טיפים, עצות והתמצאות בשטח פסטיבל אוזורה 2026 – בקרוב!",
    guideMainSubtitle: "טיפים, עצות והתמצאות בשטח פסטיבל אוזורה 2026",
    guideTopicsCount: "{count} נושאים",
    equipBackupLoaded: "הגיבוי נטען בהצלחה!",
    equipBackupInvalid: "קובץ הגיבוי אינו תקין.",
    equipBackupReadError: "שגיאה בקריאת קובץ הגיבוי.",
    equipPrintingTitle: "הדפסת {title}",
    equipCheckedCount: "סומנו",
    equipNoItemsMatch: "לא נמצאו פריטים המתאימים לסינון הנוכחי.",
    equipTopicPrintPrefix: "נושא: {heading}",
    equipQuantityLabel: "כמות",
    equipQuantityForAria: "כמות עבור {item}",
    equipNoteForAria: "הערה עבור {item}",
    equipNotePlaceholder: "מי מביא, סוג, מידה...",
    equipInfoNote: "לאחר סימון הציוד ברשימה, תוכלו לייצא אותו לאקסל, להדפיס או לשמור גיבוי.",
    equipExportBackupBtn: "ייצוא וגיבוי",
    equipExportExcelSection: "ייצוא נתונים (Excel)",
    equipExportExcelAll: "ייצוא אקסל ממותג (כל הציוד)",
    equipExportExcelChecked: "ייצוא אקסל ממותג (פריטים שסומנו בלבד)",
    equipPrintMediaSection: "הדפסה ומדיה",
    equipPrintAll: "הדפסת הרשימה (כל הציוד)",
    equipPrintChecked: "הדפסת פריטים שסומנו בלבד",
    equipExportImageAll: "ייצוא לתמונות קריאות (כל הציוד)",
    equipExportImageChecked: "ייצוא לתמונות קריאות (פריטים שסומנו בלבד)",
    equipBackupSection: "גיבוי אופליין (JSON)",
    equipSaveBackup: "שמירת קובץ גיבוי",
    equipLoadBackup: "טעינת קובץ גיבוי",
    equipSearchPlaceholder: "חיפוש פריט או רמז עזר...",
    equipClearSearch: "נקה חיפוש",
    equipFilterAll: "הכל",
    equipFilterUnchecked: "טרם סומנו",
    equipFilterChecked: "סומנו",
    equipTabShared: "קבוצתי",
    equipTabPersonal: "אישי",
    equipBrandNote: "רשימת Ozora 2026 נועדה לעזור בהיערכות. בדקו תמיד מגבלות טיסה, מזג אוויר והנחיות רשמיות של הפסטיבל.",
    equipColCategory: "קטגוריה",
    equipColItem: "פריט",
    equipColUserNote: "הערת משתמש",
    equipColOzoraNote: "הערת Ozora",
    equipColStatus: "סטטוס",
    equipStatusChecked: "סומן",
    equipStatusUnchecked: "לא סומן",
    equipNoExportItems: "לא נמצאו פריטים לייצוא בבחירה הנוכחית.",
    equipWorksheetChecked: "פריטים שסומנו",
    equipWorksheetAll: "רשימת ציוד",
    equipExportDescChecked: "ייצוא פריטים שסומנו בלבד",
    equipExportDescAll: "ייצוא כל רשימת הציוד",
    equipBrandTitle: "OZORA 2026 · רשימת ציוד לפסטיבל",
    equipWorksheetCoordination: "ציוד שסומן",
    equipWorksheetCoordinationDesc: "גיליון תיאום מהיר: רק פריטים שסומנו",
    equipWorksheetFull: "כל הרשימה",
    equipWorksheetFullDesc: "גיליון מלא: כולל פריטים שלא סומנו",
    equipPageMarker: "OZORA 2026 · עמוד {page}/{total} · ozora2026.app"
  }
};
