export const translations = {
  en: {
    title: "OZORA 2026 TIMETABLE",
    searchPlaceholder: "Search artist, stage, type...",
    favoritesOnly: "My Schedule Only",
    stageFilter: "Stages",
    dayFilter: "Days",
    simulatingTime: "Simulated Time",
    nowPlaying: "Now Playing",
    nextUp: "Next Up",
    noSetsFound: "No sets match your criteria.",
    stage: "Stage",
    time: "Time",
    type: "Type",
    allStages: "All Stages",
    allDays: "All Days",
    simulatedTimeDesc: "Drag slider to test schedule during festival",
    backToRealTime: "Use Real Time",
    favoritesEmpty: "Tap the star on any artist to add them to your custom schedule!",
    artist: "Artist",
    shareSchedule: "Share Schedule",
    copiedToClipboard: "Share link copied to clipboard!",
    sharedScheduleImported: "Shared schedule added to your favorites!",
    cookieTitle: "Cookie Preferences",
    cookieMessage: "We use cookies to improve your browsing experience and analyze site traffic.",
    cookieAcceptAll: "Accept All",
    cookieDeclineAll: "Decline All",
    cookieCustomize: "Customize Preferences",
    cookieSave: "Save My Choices",
    cookieNecessaryTitle: "Strictly Necessary",
    cookieNecessaryDesc: "Required for basic website functions (e.g. language selection, saved schedule, and consent state). Cannot be disabled.",
    cookieAnalyticsTitle: "Statistics & Performance",
    cookieAnalyticsDesc: "Collects anonymous details on site traffic, popular pages, and session duration using Google Analytics.",
    cookieFunctionalTitle: "Functional Settings",
    cookieFunctionalDesc: "Remember user display options and customizations.",
    cookieMarketingTitle: "Marketing & Targeting",
    cookieMarketingDesc: "Used to deliver relevant marketing campaigns or tracking (not used currently).",
    cookiePrivacyLink: "Privacy Policy",
    dataDisclaimer: "Set times, genres and other data may be incomplete or wrong. Always double-check on site.",
    copyright: "© 2026 Bersaglio. All rights reserved.",
    developedWithLove: "Developed with love by AI agents",
    installPrompt: "Open once with internet before the festival, then install for offline use",
    installBtn: "Install",
    installDismiss: "Not now",
    footerInstallPrompt: "Open once with internet before the festival to save it offline.",
    footerInstallBtn: "Install now",
    footerInstallHelp: "On iPhone: open this page online first, then tap Share and Add to Home Screen.",
    pwaUpdateTitle: "A new version is available",
    pwaUpdateBody: "Update now to get the latest changes.",
    pwaUpdateNow: "Update now",
    pwaUpdateSkip: "Skip",
    pwaUpdateDismiss: "Dismiss update prompt",
    priorityMust: "Must See",
    priorityWant: "Want to See",
    priorityMaybe: "Maybe",
    filterMustSee: "Must See Only",
    addNote: "Add note...",
    notePlaceholder: "Personal note (max 100 chars)",
    noteLabel: "Note",
    conflicts: "Conflicts",
    conflictsWith: "Overlaps with",
    conflictMinutes: "min",
    copyLink: "Copy Link",
    showQR: "Show QR",
    exportImage: "Export Image",
    qrTitle: "Scan to import my schedule",
    linkCopied: "Share link copied to clipboard!",
    exportTitle: "My Ozora 2026 Schedule",
    exportFooter: "Made with ozora2026.app",
    exportSuccess: "Image saved!",
    importTitle: "Someone shared their schedule with you!",
    importSetsCount: "sets",
    importAll: "Import All to My Schedule",
    saveAsFriend: "Save as Friend's Schedule",
    justView: "Just View",
    friendNamePlaceholder: "Friend's name",
    friendSchedules: "Friend Schedules",
    friendSets: "sets",
    compare: "Compare",
    remove: "Remove",
    bothPicked: "Both picked",
    onlyYou: "Only you",
    onlyFriend: "Only",
    addToMine: "Add to mine",
    comparingWith: "Comparing with",
    friendRemoved: "Friend's schedule removed",
    friendSaved: "Schedule saved!",
    maxFriendsReached: "Max 10 friend schedules",
    view: "View",
    viewingSchedule: "Viewing {name}'s Schedule",
    backToMySchedule: "Back to My Schedule",
    addToMySchedule: "Add to My Schedule",
    removeFromMySchedule: "Remove from My Schedule",
    mapTab: "Map",
    showOnMap: "Show on map",
    stageClosed: "Stage closed",
    nextOpening: "Next opening",
    walkTime: "walk",
    showAll: "Show All",
    downloadingMap: "Downloading map for offline use...",
    mapReady: "Map ready for offline use!",
    gpsUnavailable: "GPS unavailable",
    centerOnMe: "Center on me",
    navigate: "Navigate",
    viewInTimetable: "View in Timetable",
    distance: "away",
    themeAuto: "Auto",
    themeDay: "Day",
    themeSunset: "Sunset",
    themeNight: "Night",
    themeSunrise: "Sunrise",
    themePinned: "Theme locked",
    themeUnpinned: "Theme follows time",
    themeLabel: "Atmosphere",
    listenYouTube: "Listen on YouTube",
    listenSoundCloud: "Listen on SoundCloud",
    listenMusic: "Listen to music",
    viewModeGrid: "Grid View",
    viewModeStages: "Stage View",
    artistsCount: "artists",
    exportCsv: "Export to Excel (CSV)",
    printSchedule: "Print Schedule",
    exportImageCosmic: "Export Image (Cosmic Night)",
    exportImageTheme: "Export Image (Active Theme)",
    shareQuickAccess: "Share & Access",
    exportMedia: "Media & Image Export",
    exportFilesPrint: "Files & Printing"
  },
  he: {
    title: "לוח הופעות אוזורה 2026",
    searchPlaceholder: "חיפוש אמן, במה, סוג...",
    favoritesOnly: "הלוח שלי בלבד",
    stageFilter: "במות",
    dayFilter: "ימים",
    simulatingTime: "זמן מדומה",
    nowPlaying: "מנגנים עכשיו",
    nextUp: "הבאים בתור",
    noSetsFound: "לא נמצאו הופעות תואמות.",
    stage: "במה",
    time: "שעה",
    type: "סוג",
    allStages: "כל הבמות",
    allDays: "כל הימים",
    simulatedTimeDesc: "גרור את הסליידר כדי לבדוק הופעות במהלך הפסטיבל",
    backToRealTime: "חזור לזמן אמת",
    favoritesEmpty: "לחץ על הכוכב ליד שם האמן כדי להוסיף אותו ללוח האישי שלך!",
    artist: "אמן",
    shareSchedule: "שתף לוח זמנים",
    copiedToClipboard: "קישור השיתוף הועתק ללוח!",
    sharedScheduleImported: "לוח ההופעות ששותף איתך התווסף למועדפים!",
    cookieTitle: "הגדרות עוגיות (Cookies)",
    cookieMessage: "אנחנו משתמשים בקבצי עוגיות כדי לשפר את חווית הגלישה והאנליטיקס באתר.",
    cookieAcceptAll: "אישור של כל העוגיות",
    cookieDeclineAll: "דחיית עוגיות",
    cookieCustomize: "התאמת העדפות",
    cookieSave: "שמור את הבחירות שלי",
    cookieNecessaryTitle: "עוגיות הכרחיות / חיוניות",
    cookieNecessaryDesc: "עוגיות שבלעדיהן האתר לא יכול לתפקד (כמו שפת האתר, המועדפים שלך והגדרות הפרטיות הללו).",
    cookieAnalyticsTitle: "עוגיות סטטיסטיקה וביצועים",
    cookieAnalyticsDesc: "מאפשר איסוף נתונים אנונימיים על אופן השימוש באתר באמצעות גוגל אנליטיקס (עמודים פופולריים, זמן שהייה וכו').",
    cookieFunctionalTitle: "עוגיות פונקציונליות",
    cookieFunctionalDesc: "עוגיות הזוכרות את הגדרות התצוגה המותאמות אישית של המשתמש.",
    cookieMarketingTitle: "עוגיות שיווק ופרסום",
    cookieMarketingDesc: "משמשות למעקב אחר משתמשים להצגת פרסומות מותאמות אישית (אינן בשימוש כרגע באתר).",
    cookiePrivacyLink: "למדיניות הפרטיות המלאה",
    dataDisclaimer: "שעות ההופעות, הז'אנרים ומידע נוסף עשויים להיות חסרים או שגויים. תמיד יש לוודא באתר.",
    copyright: "זכויות יוצרים ל-Bersaglio © 2026",
    developedWithLove: "פותח באהבה על ידי סוכני AI",
    installPrompt: "פתחו פעם אחת עם אינטרנט לפני הפסטיבל, ואז התקינו לשימוש אופליין",
    installBtn: "התקן",
    installDismiss: "לא עכשיו",
    footerInstallPrompt: "פתחו פעם אחת עם אינטרנט לפני הפסטיבל כדי לשמור לאופליין.",
    footerInstallBtn: "הורד עכשיו",
    footerInstallHelp: "באייפון: פתחו את העמוד אונליין קודם, ואז לחצו Share ו-Add to Home Screen.",
    pwaUpdateTitle: "גרסה חדשה זמינה",
    pwaUpdateBody: "אפשר לעדכן עכשיו כדי לקבל את השינויים האחרונים.",
    pwaUpdateNow: "עדכן עכשיו",
    pwaUpdateSkip: "דלג",
    pwaUpdateDismiss: "סגור הודעת עדכון",
    priorityMust: "חובה",
    priorityWant: "רוצה לראות",
    priorityMaybe: "אולי",
    filterMustSee: "רק חובה",
    addNote: "הוסף הערה...",
    notePlaceholder: "הערה אישית (עד 100 תווים)",
    noteLabel: "הערה",
    conflicts: "התנגשויות",
    conflictsWith: "חופף עם",
    conflictMinutes: "דק׳",
    copyLink: "העתק קישור",
    showQR: "הצג QR",
    exportImage: "ייצא תמונה",
    qrTitle: "סרקו כדי לייבא את הלוח שלי",
    linkCopied: "קישור השיתוף הועתק ללוח!",
    exportTitle: "הלוח שלי — אוזורה 2026",
    exportFooter: "נוצר עם ozora2026.app",
    exportSuccess: "התמונה נשמרה!",
    importTitle: "מישהו שיתף איתך את הלוח שלו!",
    importSetsCount: "הופעות",
    importAll: "ייבא הכל ללוח שלי",
    saveAsFriend: "שמור כלוח של חבר/ה",
    justView: "רק צפייה",
    friendNamePlaceholder: "שם החבר/ה",
    friendSchedules: "לוחות חברים",
    friendSets: "הופעות",
    compare: "השווה",
    remove: "הסר",
    bothPicked: "שניכם בחרתם",
    onlyYou: "רק אתה",
    onlyFriend: "רק",
    addToMine: "הוסף ללוח שלי",
    comparingWith: "משווה עם",
    friendRemoved: "הלוח של החבר/ה הוסר",
    friendSaved: "הלוח נשמר!",
    maxFriendsReached: "ניתן לשמור עד 10 לוחות חברים",
    view: "צפייה",
    viewingSchedule: "צופה בלוח של {name}",
    backToMySchedule: "חזור ללוח שלי",
    addToMySchedule: "הוסף ללוח שלי",
    removeFromMySchedule: "הסר מהלוח שלי",
    mapTab: "מפה",
    showOnMap: "הצג במפה",
    stageClosed: "הבמה סגורה",
    nextOpening: "הפתיחה הבאה",
    walkTime: "הליכה",
    showAll: "הצג הכל",
    downloadingMap: "מוריד מפה לשימוש אופליין...",
    mapReady: "המפה מוכנה לשימוש אופליין!",
    gpsUnavailable: "GPS לא זמין",
    centerOnMe: "מרכז עליי",
    navigate: "נווט",
    viewInTimetable: "הצג בלוח",
    distance: "מרחק",
    themeAuto: "אוטומטי",
    themeDay: "יום",
    themeSunset: "שקיעה",
    themeNight: "לילה",
    themeSunrise: "זריחה",
    themePinned: "העיצוב נעול",
    themeUnpinned: "העיצוב עוקב אחרי הזמן",
    themeLabel: "אווירה",
    listenYouTube: "האזן ביוטיוב",
    listenSoundCloud: "האזן בסאונדקלאוד",
    listenMusic: "האזן למוסיקה",
    viewModeGrid: "תצוגת גריד",
    viewModeStages: "תצוגת במות",
    artistsCount: "אמנים",
    exportCsv: "ייצוא לאקסל (CSV)",
    printSchedule: "הדפסת הלוח",
    exportImageCosmic: "ייצוא לתמונה (לילה קוסמי)",
    exportImageTheme: "ייצוא לתמונה (ערכת הנושא הפעילה)",
    shareQuickAccess: "שיתוף וגישה מהירה",
    exportMedia: "מדיה וייצוא תמונה",
    exportFilesPrint: "קבצים והדפסה"
  }
};
